// StakeEngine-compatible math configuration for 13-reel Rockabilly slot
export default {
	providerName: 'stake_engine',
	gameName: 'oma_peli_rockabilly',
	gameID: '0_0_oma_peli',
	rtp: 0.96,
	gameType: 'scatter',
	numReels: 13,
	numRows: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], // 13 individual reels
	minMatchingSymbols: 5, // Need at least 5 matching symbols to win
	betModes: {
		base: {
			cost: 1.0,
			feature: true,
			buyBonus: false,
			rtp: 0.96,
			max_win: 10000.0,
		},
		bonus: {
			cost: 50.0,
			feature: false,
			buyBonus: true,
			rtp: 0.96,
			max_win: 10000.0,
		},
	},
	// Scatter game - wins based on symbol count (no paylines)
	symbols: {
		// Rockabilly symbols a-m with different value tiers
		a: { // Low value
			paytable: [
				{ '13': 500 },
				{ '12': 200 },
				{ '11': 100 },
				{ '10': 50 },
				{ '9': 25 },
				{ '8': 10 },
				{ '7': 5 },
				{ '6': 2 },
				{ '5': 1 },
			],
		},
		b: { // Low value  
			paytable: [
				{ '13': 500 },
				{ '12': 200 },
				{ '11': 100 },
				{ '10': 50 },
				{ '9': 25 },
				{ '8': 10 },
				{ '7': 5 },
				{ '6': 2 },
				{ '5': 1 },
			],
		},
		c: { // Low value
			paytable: [
				{ '13': 500 },
				{ '12': 200 },
				{ '11': 100 },
				{ '10': 50 },
				{ '9': 25 },
				{ '8': 10 },
				{ '7': 5 },
				{ '6': 2 },
				{ '5': 1 },
			],
		},
		d: { // Low value
			paytable: [
				{ '13': 500 },
				{ '12': 200 },
				{ '11': 100 },
				{ '10': 50 },
				{ '9': 25 },
				{ '8': 10 },
				{ '7': 5 },
				{ '6': 2 },
				{ '5': 1 },
			],
		},
		e: { // Low value
			paytable: [
				{ '13': 600 },
				{ '12': 250 },
				{ '11': 125 },
				{ '10': 60 },
				{ '9': 30 },
				{ '8': 12 },
				{ '7': 6 },
				{ '6': 3 },
				{ '5': 1.5 },
			],
		},
		f: { // Mid value
			paytable: [
				{ '13': 800 },
				{ '12': 300 },
				{ '11': 150 },
				{ '10': 75 },
				{ '9': 40 },
				{ '8': 15 },
				{ '7': 8 },
				{ '6': 4 },
				{ '5': 2 },
			],
		},
		g: { // Mid value
			paytable: [
				{ '13': 800 },
				{ '12': 300 },
				{ '11': 150 },
				{ '10': 75 },
				{ '9': 40 },
				{ '8': 15 },
				{ '7': 8 },
				{ '6': 4 },
				{ '5': 2 },
			],
		},
		h: { // WILD - Red_bubblegum substitutes any symbol
			paytable: [
				{ '13': 1000 },
				{ '12': 400 },
				{ '11': 200 },
				{ '10': 100 },
				{ '9': 50 },
				{ '8': 20 },
				{ '7': 10 },
				{ '6': 5 },
				{ '5': 2.5 },
			],
			special_properties: ['wild'],
		},
		i: { // Mid value
			paytable: [
				{ '13': 1000 },
				{ '12': 400 },
				{ '11': 200 },
				{ '10': 100 },
				{ '9': 50 },
				{ '8': 20 },
				{ '7': 10 },
				{ '6': 5 },
				{ '5': 2.5 },
			],
		},
		j: { // High value
			paytable: [
				{ '13': 1500 },
				{ '12': 600 },
				{ '11': 300 },
				{ '10': 150 },
				{ '9': 75 },
				{ '8': 30 },
				{ '7': 15 },
				{ '6': 8 },
				{ '5': 4 },
			],
		},
		k: { // High value
			paytable: [
				{ '13': 2000 },
				{ '12': 800 },
				{ '11': 400 },
				{ '10': 200 },
				{ '9': 100 },
				{ '8': 40 },
				{ '7': 20 },
				{ '6': 10 },
				{ '5': 5 },
			],
		},
		l: { // Premium value
			paytable: [
				{ '13': 3000 },
				{ '12': 1200 },
				{ '11': 600 },
				{ '10': 300 },
				{ '9': 150 },
				{ '8': 60 },
				{ '7': 30 },
				{ '6': 15 },
				{ '5': 7.5 },
			],
		},
		m: { // Top value (Wild/Special)
			paytable: [
				{ '13': 5000 },
				{ '12': 2000 },
				{ '11': 1000 },
				{ '10': 500 },
				{ '9': 250 },
				{ '8': 100 },
				{ '7': 50 },
				{ '6': 25 },
				{ '5': 10 },
			],
			special_properties: ['wild', 'multiplier'],
		},
		emptyslot: { // Special symbol - only on middle reel (reel 6)
			paytable: [], // No payout - special symbol
			special_properties: ['scatter'],
		},
	},
	// Reel strips for 13 individual reels
	// Each reel has weighted symbol distribution
	paddingReels: {
		basegame: [
			// Reel 0
			[
				{ name: 'a' }, { name: 'b' }, { name: 'c' }, { name: 'd' }, { name: 'e' },
				{ name: 'f' }, { name: 'g' }, { name: 'h' }, { name: 'i' }, { name: 'j' },
				{ name: 'k' }, { name: 'l' }, { name: 'm' },
				{ name: 'a' }, { name: 'b' }, { name: 'c' }, { name: 'd' }, { name: 'e' },
				{ name: 'f' }, { name: 'g' }, { name: 'h' }, { name: 'i' }, { name: 'j' },
				{ name: 'k' }, { name: 'l' },
				{ name: 'a' }, { name: 'b' }, { name: 'c' }, { name: 'd' }, { name: 'e' },
				{ name: 'f' }, { name: 'g' }, { name: 'h' }, { name: 'i' }, { name: 'j' },
			],
			// Reel 1
			[
				{ name: 'b' }, { name: 'c' }, { name: 'd' }, { name: 'e' }, { name: 'f' },
				{ name: 'g' }, { name: 'h' }, { name: 'i' }, { name: 'j' }, { name: 'k' },
				{ name: 'l' }, { name: 'm' }, { name: 'a' },
				{ name: 'b' }, { name: 'c' }, { name: 'd' }, { name: 'e' }, { name: 'f' },
				{ name: 'g' }, { name: 'h' }, { name: 'i' }, { name: 'j' }, { name: 'k' },
				{ name: 'l' }, { name: 'a' },
				{ name: 'b' }, { name: 'c' }, { name: 'd' }, { name: 'e' }, { name: 'f' },
				{ name: 'g' }, { name: 'h' }, { name: 'i' }, { name: 'j' }, { name: 'k' },
			],
			// Reel 2
			[
				{ name: 'c' }, { name: 'd' }, { name: 'e' }, { name: 'f' }, { name: 'g' },
				{ name: 'h' }, { name: 'i' }, { name: 'j' }, { name: 'k' }, { name: 'l' },
				{ name: 'm' }, { name: 'a' }, { name: 'b' },
				{ name: 'c' }, { name: 'd' }, { name: 'e' }, { name: 'f' }, { name: 'g' },
				{ name: 'h' }, { name: 'i' }, { name: 'j' }, { name: 'k' }, { name: 'l' },
				{ name: 'a' }, { name: 'b' },
				{ name: 'c' }, { name: 'd' }, { name: 'e' }, { name: 'f' }, { name: 'g' },
				{ name: 'h' }, { name: 'i' }, { name: 'j' }, { name: 'k' }, { name: 'l' },
			],
			// Reel 3
			[
				{ name: 'd' }, { name: 'e' }, { name: 'f' }, { name: 'g' }, { name: 'h' },
				{ name: 'i' }, { name: 'j' }, { name: 'k' }, { name: 'l' }, { name: 'm' },
				{ name: 'a' }, { name: 'b' }, { name: 'c' },
				{ name: 'd' }, { name: 'e' }, { name: 'f' }, { name: 'g' }, { name: 'h' },
				{ name: 'i' }, { name: 'j' }, { name: 'k' }, { name: 'l' }, { name: 'a' },
				{ name: 'b' }, { name: 'c' },
				{ name: 'd' }, { name: 'e' }, { name: 'f' }, { name: 'g' }, { name: 'h' },
				{ name: 'i' }, { name: 'j' }, { name: 'k' }, { name: 'l' }, { name: 'm' },
			],
			// Reel 4
			[
				{ name: 'e' }, { name: 'f' }, { name: 'g' }, { name: 'h' }, { name: 'i' },
				{ name: 'j' }, { name: 'k' }, { name: 'l' }, { name: 'm' }, { name: 'a' },
				{ name: 'b' }, { name: 'c' }, { name: 'd' },
				{ name: 'e' }, { name: 'f' }, { name: 'g' }, { name: 'h' }, { name: 'i' },
				{ name: 'j' }, { name: 'k' }, { name: 'l' }, { name: 'a' }, { name: 'b' },
				{ name: 'c' }, { name: 'd' },
				{ name: 'e' }, { name: 'f' }, { name: 'g' }, { name: 'h' }, { name: 'i' },
				{ name: 'j' }, { name: 'k' }, { name: 'l' }, { name: 'm' }, { name: 'a' },
			],
			// Reel 5
			[
				{ name: 'f' }, { name: 'g' }, { name: 'h' }, { name: 'i' }, { name: 'j' },
				{ name: 'k' }, { name: 'l' }, { name: 'm' }, { name: 'a' }, { name: 'b' },
				{ name: 'c' }, { name: 'd' }, { name: 'e' },
				{ name: 'f' }, { name: 'g' }, { name: 'h' }, { name: 'i' }, { name: 'j' },
				{ name: 'k' }, { name: 'l' }, { name: 'a' }, { name: 'b' }, { name: 'c' },
				{ name: 'd' }, { name: 'e' },
				{ name: 'f' }, { name: 'g' }, { name: 'h' }, { name: 'i' }, { name: 'j' },
				{ name: 'k' }, { name: 'l' }, { name: 'm' }, { name: 'a' }, { name: 'b' },
			],
			// Reel 6 (middle reel) - ONLY emptyslot and h (Red_bubblegum)
			[
				{ name: 'emptyslot' }, { name: 'h' }, { name: 'emptyslot' }, { name: 'h' },
				{ name: 'emptyslot' }, { name: 'h' }, { name: 'emptyslot' }, { name: 'h' },
				{ name: 'emptyslot' }, { name: 'h' }, { name: 'emptyslot' }, { name: 'h' },
				{ name: 'emptyslot' }, { name: 'h' }, { name: 'emptyslot' }, { name: 'h' },
				{ name: 'emptyslot' }, { name: 'h' }, { name: 'emptyslot' }, { name: 'h' },
				{ name: 'emptyslot' }, { name: 'h' }, { name: 'emptyslot' }, { name: 'h' },
				{ name: 'emptyslot' }, { name: 'h' }, { name: 'emptyslot' }, { name: 'h' },
				{ name: 'emptyslot' }, { name: 'h' }, { name: 'emptyslot' }, { name: 'h' },
				{ name: 'emptyslot' }, { name: 'h' }, { name: 'emptyslot' },
			],
			// Reel 7
			[
				{ name: 'h' }, { name: 'i' }, { name: 'j' }, { name: 'k' }, { name: 'l' },
				{ name: 'm' }, { name: 'a' }, { name: 'b' }, { name: 'c' }, { name: 'd' },
				{ name: 'e' }, { name: 'f' }, { name: 'g' },
				{ name: 'h' }, { name: 'i' }, { name: 'j' }, { name: 'k' }, { name: 'l' },
				{ name: 'a' }, { name: 'b' }, { name: 'c' }, { name: 'd' }, { name: 'e' },
				{ name: 'f' }, { name: 'g' },
				{ name: 'h' }, { name: 'i' }, { name: 'j' }, { name: 'k' }, { name: 'l' },
				{ name: 'm' }, { name: 'a' }, { name: 'b' }, { name: 'c' }, { name: 'd' },
			],
			// Reel 8
			[
				{ name: 'i' }, { name: 'j' }, { name: 'k' }, { name: 'l' }, { name: 'm' },
				{ name: 'a' }, { name: 'b' }, { name: 'c' }, { name: 'd' }, { name: 'e' },
				{ name: 'f' }, { name: 'g' }, { name: 'h' },
				{ name: 'i' }, { name: 'j' }, { name: 'k' }, { name: 'l' }, { name: 'a' },
				{ name: 'b' }, { name: 'c' }, { name: 'd' }, { name: 'e' }, { name: 'f' },
				{ name: 'g' }, { name: 'h' },
				{ name: 'i' }, { name: 'j' }, { name: 'k' }, { name: 'l' }, { name: 'm' },
				{ name: 'a' }, { name: 'b' }, { name: 'c' }, { name: 'd' }, { name: 'e' },
			],
			// Reel 9
			[
				{ name: 'j' }, { name: 'k' }, { name: 'l' }, { name: 'm' }, { name: 'a' },
				{ name: 'b' }, { name: 'c' }, { name: 'd' }, { name: 'e' }, { name: 'f' },
				{ name: 'g' }, { name: 'h' }, { name: 'i' },
				{ name: 'j' }, { name: 'k' }, { name: 'l' }, { name: 'a' }, { name: 'b' },
				{ name: 'c' }, { name: 'd' }, { name: 'e' }, { name: 'f' }, { name: 'g' },
				{ name: 'h' }, { name: 'i' },
				{ name: 'j' }, { name: 'k' }, { name: 'l' }, { name: 'm' }, { name: 'a' },
				{ name: 'b' }, { name: 'c' }, { name: 'd' }, { name: 'e' }, { name: 'f' },
			],
			// Reel 10
			[
				{ name: 'k' }, { name: 'l' }, { name: 'm' }, { name: 'a' }, { name: 'b' },
				{ name: 'c' }, { name: 'd' }, { name: 'e' }, { name: 'f' }, { name: 'g' },
				{ name: 'h' }, { name: 'i' }, { name: 'j' },
				{ name: 'k' }, { name: 'l' }, { name: 'a' }, { name: 'b' }, { name: 'c' },
				{ name: 'd' }, { name: 'e' }, { name: 'f' }, { name: 'g' }, { name: 'h' },
				{ name: 'i' }, { name: 'j' },
				{ name: 'k' }, { name: 'l' }, { name: 'm' }, { name: 'a' }, { name: 'b' },
				{ name: 'c' }, { name: 'd' }, { name: 'e' }, { name: 'f' }, { name: 'g' },
			],
			// Reel 11
			[
				{ name: 'l' }, { name: 'm' }, { name: 'a' }, { name: 'b' }, { name: 'c' },
				{ name: 'd' }, { name: 'e' }, { name: 'f' }, { name: 'g' }, { name: 'h' },
				{ name: 'i' }, { name: 'j' }, { name: 'k' },
				{ name: 'l' }, { name: 'a' }, { name: 'b' }, { name: 'c' }, { name: 'd' },
				{ name: 'e' }, { name: 'f' }, { name: 'g' }, { name: 'h' }, { name: 'i' },
				{ name: 'j' }, { name: 'k' },
				{ name: 'l' }, { name: 'm' }, { name: 'a' }, { name: 'b' }, { name: 'c' },
				{ name: 'd' }, { name: 'e' }, { name: 'f' }, { name: 'g' }, { name: 'h' },
			],
			// Reel 12
			[
				{ name: 'm' }, { name: 'a' }, { name: 'b' }, { name: 'c' }, { name: 'd' },
				{ name: 'e' }, { name: 'f' }, { name: 'g' }, { name: 'h' }, { name: 'i' },
				{ name: 'j' }, { name: 'k' }, { name: 'l' },
				{ name: 'a' }, { name: 'b' }, { name: 'c' }, { name: 'd' }, { name: 'e' },
				{ name: 'f' }, { name: 'g' }, { name: 'h' }, { name: 'i' }, { name: 'j' },
				{ name: 'k' }, { name: 'l' },
				{ name: 'm' }, { name: 'a' }, { name: 'b' }, { name: 'c' }, { name: 'd' },
				{ name: 'e' }, { name: 'f' }, { name: 'g' }, { name: 'h' }, { name: 'i' },
			],
		],
	},
};
